previewsEnabled: true
services:
  - type: web
    name: samen-front
    env: node
    plan: free
    buildCommand: yarn && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_ENV
        value: production
